apiVersion: apps/v1
kind: Deployment
metadata:
  name: okit-deploy
  namespace: default
  labels:
    app: okit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okit
      environment: dev
  template:
    metadata:
      labels:
        app: okit
        environment: dev
    spec:
      imagePullSecrets:
      - name: ocirsecret
      containers:
      - name: okit
        image: {{ .Values.imagen }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /root/.oci/config
          subPath: config
          name: ocicli
          readOnly: true
        - mountPath: /root/.oci/oci_api_key.pem
          subPath: oci_api_key.pem
          name: ocicli
          readOnly: true
      volumes:
        - name: ocicli
          secret:
            secretName: ocicli
            defaultMode: 256
---
apiVersion: v1
kind: Service
metadata:
   name: okit-service
   namespace: default
   labels:
    app: okit
spec:
   type: NodePort
   ports:
   - port: 80
     targetPort: 80
     nodePort: 30300
   selector:
     app: okit
status:
   loadBalancer: {}
