apiVersion: apps/v1
kind: Deployment
metadata:
  name: agenda-deploy
  namespace: default
  labels:
    app: agenda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agenda
      environment: dev
  template:
    metadata:
      labels:
        app: agenda
        environment: dev
    spec:
      imagePullSecrets:
      - name: ocirsecret
      containers:
      - name: agenda
        image: {{ .Values.imagen }}
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /agenda/agenda.txt
          subPath: agenda.txt
          name: agenda
          readOnly: true
      volumes:
        - name: agenda
          secret:
            secretName: agenda
            defaultMode: 256
